#lang racket/base

(require racket/contract
         racket/string
         racket/format
         racket/list
         "parser.rkt")

(provide (all-defined-out))

(define/contract (emit-python ast [output-module-name "generated_agent"])
  (->* (al-ast?) (string?) string?)
  (string-append
   (emit-header output-module-name)
   (emit-agent-vars ast)
   (emit-harness-classes ast)
   (emit-registry ast)
   (emit-footer)))

(define (emit-header module-name)
  (string-append
   (string-join
   `("\"\"\"Auto-generated by AgentLisp compiler (Racket). DO NOT EDIT HAND-WRITTEN SECTIONS.\"\"\""
     ""
     "from __future__ import annotations"
     ""
     "from typing import Any, Optional"
     ""
     "from pydantic import BaseModel, Field"
     ""
     "try:"
     "    from runtime.base_harness import BaseHarness, ExecutionTrace"
     "except ImportError:  # pragma: no cover - allow standalone import"
     "    class BaseHarness:  # type: ignore[no-redef]"
     "        def __init__(self, *a: Any, **kw: Any) -> None: ..."
     "    class ExecutionTrace(BaseModel):  # type: ignore[no-redef]"
     "        turns: list[dict[str, Any]] = Field(default_factory=list)"
     ""
     "AGENTLISP_GENERATED: bool = True"
     ,(format "MODULE_NAME: str = ~s" module-name)
     "")
   "\n")
   ;; 原为 #:after-1（string-join 无此关键字）→ 直接拼接模块名尾注
   (format "~s\n\n" module-name)))

(define (emit-agent-vars ast)
  (define lines '())
  (define agents (al-ast-agents ast))
  (when (null? agents)
    (set! lines (cons "AGENTS: dict[str, dict[str, Any]] = {}\n" lines)))
  (for ([ag (in-list agents)])
    (set! lines
          (cons
           (string-join
            (list
             (format "AGENT_NAME: str = ~s" (al-agent-name ag))
             (format "AGENT_PURPOSE: str = ~s" (al-agent-purpose ag))
             (format "AGENT_TOOLS: list[dict[str, Any]] = ~a"
                     (list->py-list (map tool->dict (al-agent-tools ag))))
             (format "AGENT_WORKFLOWS: list[dict[str, Any]] = ~a"
                     (list->py-list (map workflow->dict (al-agent-workflows ag))))
             "")
            "\n")
           lines)))
  (string-join (reverse lines) "\n"))

(define (emit-harness-classes ast)
  (string-join
   (for/list ([ag (in-list (al-ast-agents ast))])
     (define class-name (string-append (classify (al-agent-name ag)) "Harness"))
     (string-join
      (list
       (format "class ~a(BaseHarness):" class-name)
       (format "    \"\"\"Generated harness for agent ~a.\"\"\"" (al-agent-name ag))
       (format "    agent_name: str = ~s" (al-agent-name ag))
       ""
       "    def __init__(self, *args: Any, **kwargs: Any) -> None:"
       "        super().__init__("
       "            agent_cfg={"
       (format "                \"name\": ~s," (al-agent-name ag))
       (format "                \"purpose\": ~s," (al-agent-purpose ag))
       "                \"tools\": AGENT_TOOLS,"
       "                \"workflows\": AGENT_WORKFLOWS,"
       "            },"
       "            *args,"
       "            **kwargs,"
       "        )"
       ""
       "")
      "\n"))     ; 类体内部必须用换行分隔（原为空串 → 整个 class 挤在一行，Python 语法错误）
   "\n"))

(define (emit-registry ast)
  (define entries
    (for/list ([ag (in-list (al-ast-agents ast))])
      (format "    ~s: ~a" (al-agent-name ag) (string-append (classify (al-agent-name ag)) "Harness"))))
  (string-join
   `(""
     "HARNESS_REGISTRY: dict[str, type[BaseHarness]] = {"
     ,@(add-commas entries)
     "}"
     ""
     "__all__ = ["
     "    \"AGENT_NAME\","
     "    \"AGENT_PURPOSE\","
     "    \"AGENT_TOOLS\","
     "    \"AGENT_WORKFLOWS\","
     "    \"HARNESS_REGISTRY\","
     ,@(for/list ([ag (in-list (al-ast-agents ast))])
         (format "    \"~aHarness\"," (classify (al-agent-name ag))))
     "]"
     "")
   "\n"))     ; 段落必须换行分隔（原为空串 → registry/__all__/main 全挤在一行）

(define (emit-footer)
  (string-join
   '("if __name__ == \"__main__\":"
     "    import json"
     "    summary = {"
     "        \"module\": MODULE_NAME,"
     "        \"agents\": list(HARNESS_REGISTRY.keys()),"
     "    }"
     "    print(json.dumps(summary, ensure_ascii=False, indent=2))"
     "")
   "\n"))

(define (add-commas lines)
  (cond
    [(null? lines) '()]
    [(null? (cdr lines)) (list (car lines))]
    [else (cons (string-append (car lines) ",") (add-commas (cdr lines)))]))

(define (classify s)
  (define parts (string-split s #px"[-_\\s]+"))
  (string-join (map string-titlecase parts) ""))

(define (list->py-list xs)
  (if (null? xs)
      "[]"
      (string-append "[" (string-join (map ->py xs) ", ") "]")))

(define (->py v)
  (cond
    [(string? v) (format "~s" v)]
    [(symbol? v) (format "~s" (symbol->string v))]
    [(number? v) (format "~a" v)]
    [(boolean? v) (if v "True" "False")]
    [(null? v) "None"]
    [(hash? v) (hash->py-dict v)]
    [(list? v) (list->py-list v)]
    [(pair? v) (list->py-list (flatten v))]
    [else (format "~s" (format "~a" v))]))

(define (hash->py-dict h)
  (define entries
    (for/list ([(k v) (in-hash h)])
      (format "~s: ~a" (if (symbol? k) (symbol->string k) k) (->py v))))
  (string-append "{" (string-join entries ", ") "}"))

(define (tool->dict t)
  (hasheq 'name (al-tool-name t)
          'description (al-tool-description t)
          'input_schema (al-tool-input-schema t)
          'output_schema (al-tool-output-schema t)))

(define (workflow->dict w)
  (hasheq 'name (al-workflow-name w)
          'triggers (al-workflow-triggers w)
          'steps (map step->dict (al-workflow-steps w))))

(define (step->dict s)
  (hasheq 'id (al-step-id s)
          'action (action->dict (al-step-action s))
          'next (al-step-next s)
          'condition (al-step-condition s)))

(define (action->dict a)
  (if (al-atomic? a)
      (hasheq 'type "atomic"
              'name (al-atomic-name a)
              'target (al-atomic-target a)
              'method (al-atomic-method a)
              'params (al-atomic-params a))
      (hasheq 'type "custom" 'value (format "~a" a))))
