#lang racket/base
;; GENERATED by scripts/gen_patterns_v2.py -- do not edit by hand.
;; CR-41 V2 pattern-macro layer: one canonical, Core-AST-legal template per pattern.

(require (for-syntax racket/base racket/syntax racket/string)
         (for-meta 2 racket/base racket/syntax))

(provide defpriority-agent
         defdecomposition-agent
         deffsm-agent
         defevaluator-agent
         deftopic-model-agent
         defdecomposer-agent
         defguardrails-safety-agent
         defhitl-agent
         defexception-agent
         defexploration-agent)


(begin-for-syntax
  (define (v2-str-replace s from to)
    (regexp-replace* (regexp-quote from) s to))

  ;; The user's pattern plist rendered as "key=value；key2=value2" (input order kept).
  (define (v2-params->string rst)
    (let loop ((xs rst) (acc '()))
      (cond
        ((or (null? xs) (null? (cdr xs))) (string-join (reverse acc) "；"))
        (else
         (define k (car xs))
         (define ks (cond ((symbol? k) (symbol->string k))
                          ((keyword? k) (keyword->string k))
                          (else (format "~s" k))))
         (define ks* (if (regexp-match? #rx"^:" ks) (substring ks 1) ks))
         (loop (cddr xs) (cons (string-append ks* "=" (format "~s" (cadr xs))) acc))))))

  ;; {name} / {params} substitution inside template strings.
  (define (v2-subst x name params)
    (cond
      ((string? x) (v2-str-replace (v2-str-replace x "{name}" name) "{params}" params))
      ((pair? x) (cons (v2-subst (car x) name params) (v2-subst (cdr x) name params)))
      (else x)))

  ;; %name% placeholder symbol -> the agent name (符号，保持 Core AST 里 name 是 symbol)。
  (define (v2-name-fix x name)
    (cond
      ((eq? x '%name%) name)
      ((pair? x) (cons (v2-name-fix (car x) name) (v2-name-fix (cdr x) name)))
      (else x)))

  ;; 字符串替换只能用字符串：宏收到的 name 是 symbol，需先转字符串（CI 实证 contract violation）。
  (define (v2-name->string x)
    (cond ((symbol? x) (symbol->string x))
          ((string? x) x)
          (else (format "~s" x))))

  (define (v2-instantiate tmpl name rst)
    (v2-name-fix (v2-subst tmpl (v2-name->string name) (v2-params->string rst)) name))

  (define v2-templates
    (list
     (cons 'defpriority-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.2 :system-prompt "你是一个优先级队列调度 Agent（Priority）。待办任务进入优先队列后按优先级出队，同优先级按加权策略评分决出先后。 模式参数：{params}。约束：priority-level 决定出队次序，数值越大越先执行；同优先级按 policies 加权评分排序；队列清空之前不得提前结束。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "abort"))))
     (cons 'defdecomposition-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.2 :system-prompt "你是一个递归任务分解 Agent（Decomposition）。把目标拆成两层子任务，每层交给独立 scoped-worker 执行后汇总。 模式参数：{params}。约束：递归分解为 2 层子任务（decomp-level-1 / decomp-level-2）；每层由独立 scoped-worker 子 Agent 执行；子任务结果必须合并回主轨迹后才算完成。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "abort")) (:multiagent :topology orchestration :workers ((scoped-worker decomp-level-1 (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.2 :system-prompt "第一层分解 Worker：把目标拆成 2-4 个子任务。") (:tools (import-builtin bash)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 3 :on-failure "abort"))) (scoped-worker decomp-level-2 (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.2 :system-prompt "第二层分解 Worker：把子任务拆成可执行步骤。") (:tools (import-builtin bash)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 3 :on-failure "abort")))))))
     (cons 'deffsm-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个有限状态机编排 Agent（FSM）。只允许按给定转移表迁移状态，每次迁移前必须先读当前状态。 模式参数：{params}。约束：当前状态由 fsm-current-state 原子变量跟踪；状态可达性 ≥2 静态断言（每个终态至少一条入边）；非法转移必须立即终止并回报。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 1 :circuit-breaker 10 :on-failure "abort"))))
     (cons 'defevaluator-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个候选方案评估器（Evaluator）。对每个候选方案独立打分并给出排序，评分标准必须显式可复核。 模式参数：{params}。约束：Correct 段含 accuracy≥0.8 与 safety≥1.0 双阈值检查；评估标准注入 Verify 段并由 reviewer-agent 复核；未达阈值的候选必须标记 rejected 而非静默丢弃。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "pytest" :reviewer-agent "评分标准复核器") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "fallback-model"))))
     (cons 'deftopic-model-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个主题建模 Agent（Topic Model）。把输入语料聚类成主题，并把每个主题的标签集合交给下游。 模式参数：{params}。约束：主题聚类由 scoped-worker(topic-processor) 执行；topics 子树分类器输出标签集合；低置信度主题必须保留待人工复核。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "abort")) (:multiagent :topology orchestration :workers ((scoped-worker topic-processor (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.2 :system-prompt "主题聚类 Worker：对语料做主题聚类并输出标签集合。") (:tools (import-builtin bash)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 3 :on-failure "abort")))))))
     (cons 'defdecomposer-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个结构化提取 Agent（Decomposer）。只输出符合给定 schema 的字段，类型不符的字段一律拒绝。 模式参数：{params}。约束：Constrain 段注入 2 条 decomposer-schema-field-type-check（iso-date / double）；字段类型不符必须拒绝输出并回报字段名；Schema 校验先于任何写操作。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "abort"))))
     (cons 'defguardrails-safety-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个安全护栏 Agent（Guardrails & Safety）。任何工具调用前先过护栏三段校验，违规即阻断。 模式参数：{params}。约束：Harness 三段 guardrails 钩子（constrain / verify / correct）；on-violation 触发 Verify→Correct 回路；复用 NFR-SEC 基线，不得绕过护栏直接执行。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval ("all") :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "pytest" :reviewer-agent "护栏合规复核器") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "abort"))))
     (cons 'defhitl-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个人在回路 Agent（HITL）。关键动作必须等待人类批准信号，未获批不得继续。 模式参数：{params}。约束：Constrain 段 human-approval-required-before 生效；Verify 段 waiting-for-human-signal 状态可观测；人类拒绝后进入终止分支而非重试。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval ("all") :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 1 :circuit-breaker 10 :on-failure "ask-human"))))
     (cons 'defexception-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.0 :system-prompt "你是一个异常恢复 Agent（Exception Handling & Recovery）。失败按三层重试阶梯恢复，超出预算转入死信队列。 模式参数：{params}。约束：Correct 段 3 层 on-failure retry（retry=3, backoff=1.5x）；Harness Constrain+Verify+Correct 三层不少；熔断后进入死信队列并通知人工。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 3 :circuit-breaker 5 :on-failure "fallback-model"))))
     (cons 'defexploration-agent
           '(define-agent %name% (:model :provider "anthropic" :name "claude-3-7-sonnet" :temperature 0.3 :system-prompt "你是一个探索式试错 Agent（Exploration & Discovery）。在预算内探索候选路径，收敛即停止并回报最优解。 模式参数：{params}。约束：Verify 段 budget + convergence 两条检查；Correct 段 expand-more-candidates 扩展候选；探索预算耗尽或收敛阈值触发即停止。") (:tools (import-builtin bash)) (:context :memory-policy (:markdown-fs "./memory/{name}.md" :layers (L0-Abstract) :auto-append #f) :skills () :status-bar (:step-count #t :current-branch #f :test-status #t)) (:harness (:constrain :require-human-approval () :forbidden-commands ("rm -rf")) (:verify :json-schema #t :linter-check #f :test-runner "") (:correct :max-retries 2 :circuit-breaker 5 :on-failure "ask-human")))))))

(define-syntax (defpriority-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax priority01_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defpriority-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defpriority-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defdecomposition-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax decomp02_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defdecomposition-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defdecomposition-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (deffsm-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax fsm03_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'deffsm-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'deffsm-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defevaluator-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax eval04_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defevaluator-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defevaluator-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (deftopic-model-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax topic05_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'deftopic-model-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'deftopic-model-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defdecomposer-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax decom06_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defdecomposer-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defdecomposer-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defguardrails-safety-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax guard07_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defguardrails-safety-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defguardrails-safety-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defhitl-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax hitl08_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defhitl-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defhitl-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defexception-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax exc09_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defexception-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defexception-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))

(define-syntax (defexploration-agent stx)
  (syntax-case stx ()
    ;; HC FIRST -- fixture 写死名分支（first-match 语义，CR-41 AC-3 锚）
    ((_ name* . rst*)
     (free-identifier=? (syntax explore10_hc) (syntax name*))
       #`(quote #,(v2-instantiate (cdr (assq 'defexploration-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))
    ;; GENERIC SECOND -- 任意名 + 任意 plist；与 HC 共用同一模板，仅 name/参数不同
    ((_ name* . rst*)
       #`(quote #,(v2-instantiate (cdr (assq 'defexploration-agent v2-templates))
                              (syntax->datum (syntax name*))
                              (syntax->datum (syntax rst*)))))))
